### ISSUE TITLE
Bench error

### ISSUE THREAD

**Issue by zamazan4ik** [anacrolix/possum#1]
When I tried to run the benchmarks with `cargo bench`, I got the following error:

```
Benchmarking clonefile/hello/4.0 kiB: Warming up for 500.00 msthread 'main' panicked at benches/clonefile.rs:25:26:
called `Result::unwrap()` on an `Err` value: io error: Os { code: 18, kind: CrossesDevices, message: "Invalid cross-device link" }

Caused by:
    Invalid cross-device link (os error 18)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: bench failed, to rerun pass `--bench possum`
```

Environment information:

* OS: Fedora 39
* Kernel version: 6.7.4
* Rustc version: 1.76

**Comment by anacrolix** [comment]
Thanks! I'll take a look. What is your filesystem?

**Comment by zamazan4ik** [comment]
> What is your filesystem?

BTRFS

**Comment by anacrolix** [comment]
Thanks for this. I discovered a similar problem due to having /tmp mounted on tmpfs and my repo clone dir being on another filesystem. I think the fix I produce for that will fix your problem too.

**Comment by anacrolix** [comment]
@zamazan4ik if you could test from `main` that would be appreciated.

**Comment by zamazan4ik** [comment]
Yep, now `cargo bench` works fine. Thanks a lot for the quick fix!

**Comment by anacrolix** [comment]
Thank you, I hope you find it useful
